---
title: "Assignment Guide <br>    <mark>Crafting your critique</mark>   <br> "
title-block-banner: "#001B35" # banner.png
title-block-banner-color: body-bg
format:
# pdf: default
 html:
   toc: true
   toc-location: left
   theme: michigan.scss
css: styles.css
execute:
  echo: false
  engine: knitr
---

# The Main Assignment: Revise, Revise, Revise
    
The main assignments for this class all build to one highly-polished op-ed critiquing how an organization or group of organizations is addressing or failing to address climate change. 

These assignments are motivated by the observation that politics is fundamentally an organized activity. Thus, the critiques we develop in this class will target organizations. In your opinion, are they choosing the right battles? Are they taking the right positions? Are they framing the issues in the most effective way? Is their theory of change (or resistance to change) realistic?

Critiquing those we severely disagree with is easy, but they are also the least likely to listen to you. Thus, the critiques you develop in this class will be aimed at the organizations you see as having the best chance of making a positive difference in the world---specifically, the organizations for whom you hope to work. You may not know what your future career looks like; that is fine. Perhaps you will find an organization or cause that inspires you in this class. Or perhaps you have a very clear idea of your future career. In that case, this class will challenge you to think about how organizations in your intended field of work engage in politics and policymaking---and how they might do so differently. It is not a requirement that the organizations you address are activist organizations. Indeed, activist organizations may be the most difficult to critique because they already have a well-developed approach to politics and policy. You may even see yourself working for an organization that is currently strongly opposed to most proposed climate policies; that is fine. For example, if you aim to work at Exxon-Mobil, you might look to Business School scholarship to formulate a critique like [this one](https://ssir.org/articles/entry/time_to_put_the_fossil_fuel_industry_into_hospice). 


### Find your voice

In the first third of the class, you develop five op-ed ideas and attempt to write an introduction for each. Along the way, you will identify organizations that you might want to work for (i.e., potential targets for your critique), develop ten possible lines of critique in the form of headlines, and then begin to flesh out five of them by writing the first 200 words of a potential op-ed. 


- `Assignment 1` A list of the top twenty organizations for whom you would like to work and a one-sentence summary of how they engage (or avoid engaging) in climate politics or policy. If the organization has more than 100 employees, specify a unit within the organization.^[Most organizations have an email list---I suggest signing up, both for the assignments in this class and your future career.] 
- `Assignment 2` Ten op-ed-style headlines, each critiquing a different organization from Assignment 1.
- `Assignment 3` Five revised headlines and the first 200 words for each (+ annotated bibliographies, which should appear in footnotes or endnotes and do not count toward the word limit) 

Include a <mark> word count</mark>  between the title and the essay.  I am expecting the quality of writing where every word you must cut to hit the target is painful. Thus, getting in under the word limit should be a major challenge with this assignment, and I expect the word count to be nearly exactly (perhaps a few words shorter) the word limit.

An <mark> annotated bibliography</mark>  in footnotes or endnotes means two things: 

1. Bibliography means that it cites factual claims that are not common knowledge, including the <mark> title, author, year, and a hyperlink</mark>  to the source wherever possible.  References do not count toward the word limit and should be single-spaced. References must be hyperlinked wherever possible. Please try to link to stable public URLs. For journal articles, DOI URLs are best (e.g., https://doi.org/10.1177/1086026619858874), then some other stable repository like JSTOR or the publisher's web page (e.g., https://www.jstor.org/stable/j.ctt7t5st or https://journals.sagepub.com/doi/10.1177/1086026619858874) if you can't find the DOI URL. I will be checking to ensure that the source is appropriate for an op-ed (i.e., likely to be perceived as legitimate by your audience) and that it supports the claim made in the essay's text. Fabricated sources are unacceptable, and the relationship between claim and evidence is critical.

2. Annotated means that it may include any additional context to help your reader understand <mark> why this source is important</mark>  or why it supports the claim. If these are obvious, there is no need to annotate. Annotation is optional. It allows you to elaborate in ways you cannot in the tight word limit of the main essay. 

Use <mark> footnotes or end notes</mark>  to construct your annotated bibliographies to make it easier for your peer reviewers, myself, and future editors to connect what you say in the essay to the citation. Use Arabic numerals, not roman numerals.^[If your op-ed is published, citations will likely take the form of hyperlinks, perhaps with end notes or margin notes for some online publications.]


### Craft your critique 

In the middle third of the semester, you will narrow your focus to three ideas and then two ideas and write the first half of each through multiple rounds of revision. 

I expect the annotated bibliographies to grow significantly as you respond to critiques, bolster your argument, and respond to possible counter-arguments. 

As above, include a word count between the title and the essay.

- `Assignment 4` Three revised headlines and the first 400 words for each + annotated bibliographies + a link to a google sheet with one row for each bit of feedback you received and how you are addressing it
- `Assignment 5` Two revised first 400 words + annotated bibliographies + the link to your revision tracking google sheet


#### Responding to comments 

Each time you submit your revised essays, you must include a Google sheet detailing your thoughtful responses to all of the comments you have received thus far. This spreadsheet must have a row for each suggestion and columns with the exact text of the suggestion, who made it, what you think about it, and the change (if any) made to the essay. This is your opportunity to show your work in doing the revision. 

To be clear, you do not need to include all of my exact comments in the spreadsheet (though you are welcome to do so if you are comfortable sharing them); paraphrasing is fine. The key is to communicate the gist of each bit of feedback so that your peer reviewer can help you make sure it is "thoughtfully addressed" in the next draft. 

For example: 

- if I had a bunch of spelling and grammar notes; you don't need a line for each one. Just saying "Grammar" | "All fixed" on one line is fine.  
- if I told you that something was factually incorrect, you don't need to include my exact words, just something like "Revise description of X" is fine.

This spreadsheet will grow longer as you receive more suggestions from myself and your peers. 

You must share this spreadsheet with me each time your resubmit your revised essay(s). <mark>Put a link to your google sheet at the top of your essay.</mark> I am primarily grading on how you respond to feedback, so I will use this spreadsheet as something like rubric to assess your thoughtful engagment with my feedback and your peer reviews.

It is up to you whether you want to share this spreadsheet with your peer reviewers. 


### Hone your critique 

Through additional rounds of revision, you will further hone one of your critiques, improving your logic and writing (writing can always be improved). 

Again, I expect your annotated bibliography to grow significantly as you respond to critiques, bolster your argument, and respond to possible counter-arguments. 

- `Assignment 6` One 750-800 word op-ed + annotated bibliography + the link to your revision tracking google sheet
- `Assignment 7` Revised op-ed  + annotated bibliography + the link to your revision tracking google sheet
- `Assignment 8` Final op-ed + annotated bibliography + the link to your revision tracking google sheet

# Assessment 

Assessment is based on your <mark> thoughtful engagement with the ideas</mark>  in the reading and with my feedback on your writing. Because op-eds are not formulaic---there is no closed list of ways to be persuasive---I have found it unworkable to use a rubric that assigns certain points for doing certain things. Instead, you should consider the feedback you receive from me and your peer reviews to be the "rubric" for the next version. <mark> I am mostly grading on how you respond to feedback.</mark>  This does not mean that you must adopt every suggested change----just that you thoughtfully engage with them. You may choose not to adopt a change or go in a direction I suggest; that is totally fine as long as you have a good reason. If you would like, you can include revision comments on the document in Canvas addressing any points where you feel context is needed for me to understand how you incorporated feedback.


# Resouces 

## Best Practices

- [SSN: Best Practices for Writing a Compelling Op-ed](https://scholars.org/resource/how-best-practices-writing-compelling-oped)
- [SSN: Best Practices for Pitching an Op-ed](https://scholars.org/resource/how-best-practices-pitching-oped)
- [Advice from Beth from Ford's Writing Center](https://docs.google.com/presentation/d/1JeckBThHuoTKYyMLmdxQdsix8VCOi-Gv/edit?usp=sharing&ouid=107169079891814854171&rtpof=true&sd=true)


## Guidance 


While I concluded that rubrics that other instructors use for op-eds are unworkable *as rubrics* for grading, you may still find helpful guidance in them. There are many on the internet. Here is some of the guidance that is commonly used to assess op-ed assignments: 


Thesis/purpose/genre:

- There is a clearly stated opinion toward the beginning of the article, which continues throughout.
- Conveys a strong, clear thesis/message to the reader that is appropriate for an op-ed and reflects the actual argument
- Has the characteristics of an op-ed as shown in the sample op-eds
- Supports the opinion with reasons that include details connected to the opinion

[Lede](https://keybridgecommunications.com/whats-lede-2/) 

- The lede brings the reader into the story

Organization/focus:

- The essay is well organized overall. Individual paragraphs are well-focused and relate to your thesis/message
- Argument is easy to follow: clear claims/points, helpful reader “signposts” (including transitions), logical train of thought, and a clear distinction between your own & sources’ ideas
- Contains logical reasons for the stated opinion
- Reasons are written to convince the appropriate audience
- Contains examples of rhetorical devices, logical/emotional language, and action words

Sources, context, & evidence:

- You've supported your argument with enough evidence. This material is also well chosen and clearly explained, enough for readers to understand 
- The op-ed contains all necessary background information, but not more than necessary
- Any quotations are well chosen (relevant & meaningful)
- Any personal examples and observations are not too long and very relevant to your larger thesis/message

Analysis:

- Analysis is thoughtful, specific, and based on relevant evidence. You’ve explained ideas & connections
- Avoid vague and repetition

Sentence editing, flow, and citations:

- Clear sentences & correct grammar, language use, punctuation, format, etc.
- Good sentence variety, flow, style, and tone (appropriate for an op-ed but not overly informal)
- Cites quotes and/or ideas from sources correctly

The best guidance I have heard from prolific op-ed writers is to **read a lot of op-eds and think about why they work or don't work.** Again, there are many ways to be persuasive, and the task here is to find your voice and workshop your writing. 


## Example op-eds

Questions for Reflection:

1. How would you characterize the differences in tone among the example op-eds? Are there
tonal shifts within each op-ed (i.e., does the op-ed begin in one tone and shift to another)?
How might each writer’s tonal choices have been strategic—i.e., intended to enhance
persuasiveness?  
2. What is each op-ed’s apparent purpose (desired effect on readers), and how does
organization (structure, ordering) aid or hinder that purpose?
3. What sorts of evidence does each writer use to support claims? Is the evidence adequate
to persuade? Why or why not?  
4. Where does the writer anticipate reader resistance? How do you know? What tactics does
the writer use to overcome this resistance?

> [Humanity Is Facing a Great Injustice. The World Bank Must Respond](https://www.nytimes.com/2023/03/18/opinion/world-bank-climate-change.html) by the NYT Editorial Board via [proquest](https://www.proquest.com/news/docview/2788890406/96ABFB8014664952PQ)

> [Exxon Mobil’s Pioneer Acquisition Is a Direct Threat to Democracy](https://www.nytimes.com/2023/10/18/opinion/exxon-pioneer-climate-change.html)  by Jeff Colgan via [proquest](https://www.proquest.com/docview/2878239656/AFEBE8014502402DPQ)

> [The Climate Solution That’s Horrible for the Climate](https://www.nytimes.com/2023/06/06/opinion/climate-change-biofuels-corn-ethanol.html) via [proquest](https://www.proquest.com/docview/2878239656/AFEBE8014502402DPQ)

> [I’m a Scientist Who Spoke Up About Climate Change. My Employer Fired Me.](https://www.nytimes.com/2023/01/10/opinion/scientist-fired-climate-change-activism.html)

> Rumble at the Sierra Club via [proquest](https://www.proquest.com/docview/432709597)

> [The Pope’s Journey to Climate Outrage](https://www.nytimes.com/2023/10/11/opinion/the-popes-journey-to-climate-outrage.html) by David Wallace-Wells via [proquest](https://www.proquest.com/docview/2875467846/E16DE7745E4B4754PQ)

> [Georgia’s Unique Runoff System, a Product of Institutional Racism by Shaher Zakaria](https://mjpa.umich.edu/2021/01/14/georgias-unique-runoff-system-a-product-of-institutional-racism/)

> [The Patent System is Failing to Promote Pharmaceutical Innovation by Christina Del Grec](https://mjpa.umich.edu/2021/12/01/the-patent-system-is-failing-to-promote-pharmaceutical-innovation/)

> [Here Is What Is Really Strangling the Energy Transition](https://www.nytimes.com/2022/12/16/opinion/solar-wind-electricity.html)

> [The Way to Slow Climate Change Is as Close as Your City Hall or School Board](https://www.nytimes.com/2022/08/26/opinion/climate-change-political-action.html)

> [What Will Happen to Your Next Home if Builders Get Their Way? A lobby is trying to block codes that save homeowners money and fight climate change.](https://www.nytimes.com/2021/01/21/opinion/homes-climate-change-building-codes-biden.html)

> [When Utility Money Talks: Corruption scandals in Ohio and Illinois reveal an unsavory underside to the politics of energy.](https://www.nytimes.com/2020/08/02/opinion/utility-corruption-energy.html)

> 


And here's a piece by two climate activists trying to influence policy:

> [Will Lawmakers Sacrifice Our Health and Safety to Get a Debt Ceiling Deal?](https://www.nytimes.com/2023/05/26/opinion/debt-ceiling-clean-energy-oil-gas-environmental-justice.html) via [proquest]


<!--NOTES 

Overall, good work on the revision.

Here are a few things to keep working on: 
- justification for "should" statements (a campaign promise is good, but can we go deeper, perhaps to arguments rooted in history or moral philosophy that people have not encountered before? Or perhaps put what you are calling attention to in the context of things that people think matter ---i.e., if you think x matters, then you must believe that y matters even more.)
- relatedly, responses to critics
- specificity (the BLM gigawatt goal is good; what else? "awareness" is still vague. ). Research will help.
- lead with the conflict rather than background facts. Foreground your most controversial opinion
---> 


# Presentations

While the main focus of this class is persuasive writing, there is a small related assignment to give a short (2-3-minute) presentation. 

The presentation assignment gives you practice testing out your argument and presentation skills. This is an opportunity to get quick feedback from the class. I also find that I am able to arrive at more elegant ways to say things when I say them out loud. It engages different parts of the brain and is a great way to workshop ideas.

This is intended to be a **low-stakes practice** oral presentation. It is ungraded: I award points just for doing it. 

It is also intended as an opportunity to get constructive feedback on your line of critique and how you are pitching it. 

I hope you will find it valuable enough that you will want to do it again, but you are only required to do it once. 

We will do up to 2 pitches per day. While you are welcome to do more than one, the first priority goes to those practicing for the first time. 

I've noticed a tendency for some presenters to offer a lot of preface and explanation before going into the heart of their pitch. I think you are better off without it. 

You want feedback on the pitch itself, including on how compelling the hook is (i.e., how you are getting people's attention and why people should care) and the clarity of your BLUF (Bottom Line Up Front, i.e., the clarity of your thesis statement/argument).  

Thus, when you get up to present, I would just launch right in and grab people's attention (unless you are thinking about pitching it to a paper with a different audience than the NYT, in which case that is helpful context.)


# Peer Reviews 

My expectation for the peer review is a significant and thoughtful engagement with each op-ed's ideas, as well as detailed notes on the writing (similar to what I gave you all in our meetings). This is an exercise in constructive critique, so there must be suggestions for improvement.

This means <mark> at least a page of written feedback</mark>  (when reviewing multiple essays, this minimum is for all of them combined---though a page on each essay would be great), <mark> as well as some notes or markup of their writing.</mark>  Writing can always be improved. 

### How to submit your review

You can use the <mark> markup features on Canvas</mark>  as you read. </mark> Your written critique should then be uploaded for the peer critique assignment **and** sent to your colleague.</mark>  (You should be able to share a Google Doc or attach a file in the "Comments for this Attempt" bar on Canvas.) <mark> Make sure to submit it in both places.</mark>  The assignment upload goes to me so that you get credit for the assignment. The "Comments for this attempt" make it available to your colleague.

Please let me know if you have any questions. Giving helpful critiques is a nuanced art, and I am happy to talk it through with you. 

### Tips on peer reviews

From [Pedagogy in Action](https://serc.carleton.edu/sp/library/peerreview/tips.html): 

- Before you even make your first comment, read the document all the way through.
- Make sure you leave enough time for you to read through, respond, and for your peer to edit his/her document with your comments before any deadlines.
- If you are provided with a feedback form to fill out and something is unclear, do not ignore the item but ask the instructor for clarification.
- Point out the strengths as well as the weaknesses of the document.
- Offer suggestions, not commands.
- Editorial comments should be appropriate and constructive. There is no need to be rude. Be respectful and considerate of the writer's feelings.
- Be sure that your comments are clear and text-specific so that your peer will know what you are referring to (for example, terms such as "unclear" or "vague" are too general to be helpful).
- As a reader, raise questions that cross your mind, points that may have not occurred to your peer author.
- Try not to overwhelm your peer with too much commentary. Follow the feedback form and the issues you are supposed to address.
- Be careful not to let your own opinions bias your review (for example, don't suggest that your peer completely rewrite the paper just because you don't agree with his/her point of view).
- Reread your comments before passing them on to your peer. Make sure all your comments make sense and are easy to follow.
- Avoid turning your peer's paper into your paper.
