
## What might a conservative rubric for 2028 candidate climate plans include? 

Remember, the political "right" is not a monolith; it's a fusion of often-contrasting aims.


- Libertarian: Government should only protect private property, contracts, and private torts.

- Anarchocapitalist: Corporations should govern; there should be no government.

- Traditionalist/conservative: Government should maintain current ways of life; slow change/mitigate disruption to social/economic roles and built and natural environments.

- Restorationist/Reactionary: Government should move society back to a previous state (real or imagined).

- Ethno-nationalist/Fascist: Government should forge a strong national (usually ethnic) identity by cleansing the nation of nonconforming people, ideas, and cultural objects. 

- Religious fundamentalist: Government should enforce divine law. <!--, empowering certain religious leaders to say what it is-->

- Nationalist-Isolationist/anti-globalist: The government should not interfere in or be concerned with affairs abroad.

- Nationalist-Hawks/neoconservative: Government should maintain regional/global dominance through military force.

- Economic Nationalist: The government should pursue economic dominance through trade and/or industrial policy.


