---
title: "Notes on *After Nature* by Jedediah Purdy"
format: html
---


Anti-politics in the Providential view of nature

- God has given the natural world to man and demands cultivation. This is not up for political debate; it is the natural (Divine) order of the world
- Manifest Destiny: God wants white settlement to advance across the North American content. It is destiny, not up for debate
- The Frontier as anti-politics: the ever-expanding frontier of white settlement provided an individualist escape from political conflicts seen in Europe. Rather than being forced to engage in politics and deciding things collectively, people were able just to leave the community
- Frontier thesis assumption (related to stages of development theory): the process of clearing and settling was a "natural" progression, not a project of war and ethnic cleansing

Anti-politics in the Romantic View

- Nature is sacred (or, at least, certain landscapes are). Secular cathedrals demand preservation as a moral imperative
- Romantics argued with utilitarians, but instead of arguing on political/democratic grounds (i.e., that questions of how to manage landscapes should be up for debate), they argued that they were the real experts, as devotees of nature, uniquely able to grasp aesthetic values
- Initially, the policy was to make parks and encourage pilgrimage. Later, wilderness: the near exclusion of humans from some areas. All in a very top-down way, often requiring the forced removal of the people who lived there

Anti-politics in managerialism / utilitarianism (Purdy lumps together these two approaches, which are related but not synonymous)

- Resources (including timber and human resources) should be managed by experts to achieve the greatest good for the greatest many—technocracy, not democracy. 
- Natural and social systems are so complex that leaving them up to individuals does not advance the public good. People do not know what is good for them or the sustainability of the resource
- Supported US imperialism since legitimate government was assumed to be based on efficient administration, not democracy
- Cost-benefit analysis is a modern form that dominates US environmental policymaking

Anti-politics in the Ecological View

- Ecosystems are complex, so policy should be written by experts. Again, technocracy, not democracy. 
- Ecosystems are complex, and central management is difficult, so policy should instead put a price on everything and establish markets to align individual choices with ecological impacts. Because there are no "natural" prices; experts must price everything...starting to slip into a version of utilitarianism without managerialism or cost-benefit analysis. 
- Green authoritarianism/eco-fascism in the name of stable ecosystems
- Misanthropy and eco-terrorism (I'm not sure that Purdy mentions this one, but it seems to be most inspired by ecological thinking) 
